version: '3'

services:
  edpn-frontend-production:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: production/edpn-frontend:latest
    ports:
      - '3003:3000'
